CREATE TABLE SO_ROLE
(
    ID      INT PRIMARY KEY,
    ROLE    VARCHAR(15) NOT NULL UNIQUE
);
-- INSERT ROLES FOR USERS
INSERT INTO SO_ROLE
VALUES (1, 'ADMIN');
INSERT INTO SO_ROLE
VALUES (2, 'SELLER');
INSERT INTO SO_ROLE
VALUES (3, 'OPS');
INSERT INTO SO_ROLE
VALUES (4, 'SUPER_ADMIN');

-- USER TABLE
CREATE TABLE SO_USERS
(
    ID            UUID PRIMARY KEY,
    EMAIL         VARCHAR(140) NOT NULL,
    FULL_NAME     VARCHAR(120) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    ROLE_ID       INT NOT NULL,
    ENABLED       BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT SO_UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT SO_FK_USERS_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SO_ROLE(ID)
);