CREATE TABLE SO_ROLE
(
    ID   INT PRIMARY KEY,
    ROLE VARCHAR(15) NOT NULL UNIQUE
);
-- STATE TABLE
CREATE TABLE SO_STATES
(
    STATE_ID    INT PRIMARY KEY,
    STATE_NAME  VARCHAR(100) NOT NULL,
    STATE_CODE  VARCHAR(10)  NOT NULL UNIQUE,
    REGION_TYPE VARCHAR(20)  NOT NULL,
    COUNTRY     VARCHAR(50) DEFAULT 'India'
);

-- USER TABLE
CREATE TABLE SO_USERS
(
    ID            UUID PRIMARY KEY,
    EMAIL         VARCHAR(140) NOT NULL,
    FULL_NAME     VARCHAR(120) NOT NULL,
    PASSWORD_HASH VARCHAR(256) NOT NULL,
    ROLE_ID       INT          NOT NULL,
    ENABLED       BOOLEAN   DEFAULT TRUE,
    CREATED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP,
    CONSTRAINT SO_UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT SO_FK_USERS_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SO_ROLE (ID)
);

--CREATE SO_PICKUP
CREATE TABLE SO_PICKUP_ADDRESS
(
    ID            UUID PRIMARY KEY,
    LABEL         VARCHAR(48) NOT NULL,
    USER_ID       UUID        NOT NULL,
    ISD_CODE VARCHAR(3) NOT NULL,
    PHONE         VARCHAR(10) NOT NULL,
    ADDRESS_LINE1 VARCHAR(256),
    ADDRESS_LINE2 VARCHAR(256),
    CITY          VARCHAR(200) NOT NULL,
    STATE_ID      INT NOT NULL,
    PIN_CODE      VARCHAR(6) NOT NULL,
    IS_DEFAULT    BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PICKUP_USER_ID FOREIGN KEY (USER_ID) REFERENCES SO_USERS (ID),
    CONSTRAINT FK_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES SO_STATES (STATE_ID)
);

-- CREATE INDEX FOR PICK_UP ADDRESS

CREATE INDEX SO_IDX_PICKUP_STATE_ID ON SO_PICKUP_ADDRESS (STATE_ID);