-- NOTIFICATION LOG TABLE
CREATE TABLE SO_NOTIFICATION_LOG
(
    ID              BIGSERIAL PRIMARY KEY,
    IDEMPOTENCY_KEY VARCHAR(100) NOT NULL,
    USER_ID         UUID,
    CHANNEL         VARCHAR(20)  NOT NULL,
    PURPOSE         VARCHAR(40)  NOT NULL,
    RECIPIENT       VARCHAR(150) NOT NULL,
    PROVIDER        VARCHAR(30),
    PROVIDER_MSG_ID VARCHAR(100),
    STATUS          VARCHAR(20)  NOT NULL,
    ERROR           VARCHAR(500),
    ATTEMPTS        INT          NOT NULL DEFAULT 0,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT SO_UQ_NOTIFICATION_LOG_IDEMPOTENCY_KEY UNIQUE (IDEMPOTENCY_KEY),
    CONSTRAINT SO_FK_NOTIFICATION_LOG_USER_ID FOREIGN KEY (USER_ID) REFERENCES SO_USERS (ID)
);

CREATE INDEX SO_IDX_NOTIFICATION_LOG_PROVIDER_MSG_ID ON SO_NOTIFICATION_LOG (PROVIDER_MSG_ID);
CREATE INDEX SO_IDX_NOTIFICATION_LOG_RECIPIENT ON SO_NOTIFICATION_LOG (RECIPIENT);
